source "http://rubygems.org"
#gem "rake", "=1.3.1"
gem "eventmachine_httpserver"
gem "sanitize"
gem "amqp"
gem "em-websocket"
gem "rspec"
gem "rails"
gem "sinatra"
gem "rake"
gem "thin"
gem "mysql"
gem "em-http-request"
gem "oauth2"
gem "rest-client"
gem "uuid"
gem "daemon-kit"
